name: Cargo Build & Test

on:
  # push:
  pull_request:

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  set_env:
    runs-on: ubuntu-latest
    name: "Create Setting.toml file"
    environment: PROD
    steps:
      - run: |
          touch Setting.toml
          echo [server] >> Setting.toml
          echo port = ${{ vars.APP_PORT }} >> Setting.toml
          echo [database] >> Setting.toml
          echo host = ${{ secrets.DB_HOST }} >> Setting.toml
          echo user = ${{ secrets.DB_USER }} >> Setting.toml
          echo password = ${{ secrets.DB_PASSWORD }} >> Setting.toml
          echo dbname = ${{ secrets.DB_DBNAME }} >> Setting.toml
          echo schema = ${{ secrets.DB_SCHEMA }} >> Setting.toml

  build_production:
    runs-on: ubuntu-latest
    name: "Build for release"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build for release
        run: cargo build --release
        shell: bash

  # build_and_test:
  #   name: Rust project - latest
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       toolchain:
  #         - stable
  #         - beta
  #         - nightly
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
  #     - run: cargo build --verbose
  #     - run: cargo test --verbose
