name: Deploy To Cloud

on:
  push:
    branches:
      - develop

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "set-up env"
        run: |
          touch Setting.toml
          echo [server] >> Setting.toml
          echo port = ${{ vars.APP_PORT }} >> Setting.toml
          echo [database] >> Setting.toml
          echo host = ${{ secrets.DB_HOST }} >> Setting.toml
          echo user = ${{ secrets.DB_USER }} >> Setting.toml
          echo password = ${{ secrets.DB_PASSWORD }} >> Setting.toml
          echo dbname = ${{ secrets.DB_DBNAME }} >> Setting.toml
          echo schema = ${{ secrets.DB_SCHEMA }} >> Setting.toml

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: "${{ secrets.GOOGLE_PROJECT_ID }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/rust-axum-todo-list:latest .
          docker push gcr.io/asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/rust-axum-todo-list:latest
